### ISSUE TITLE
Use the os library for paths

### ISSUE THREAD

**Issue by twieteddy** [vlouvet/change_desktopy#1]
Use os.path.join to concat paths correctly and os.path.expanduser("~") to get your home directory.
`import os`
`directory = os.path.join(os.path.expanduser("~"), "Desktop", "bgs")`
`imagePath = os.path.join(directory, "test.png")`

Values:
`C:\Users\alma\bgs`
 `C:\Users\alma\bgs\test.png`

Separators will be determined automatically:
`\` on Windows, `/` on all other operating systems, as far as I am aware.

Your functions don't need to return anything, so you can remove `return 0;`

**Comment by vlouvet** [comment]
I appreciate the feedback, the shutil approach was kind of sloppy, so I re-wrote it using the input you provided. 

Also, VS Code was being weird about my function unless I returned something, on a second look that issue no longer happens now so I've updated that part as well.

Thanks for all the help!
